title: Rahul Gupta # your name (or website title) here
logo: "/images/rahulGupta.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  This is my personal portal for Data Science and Machine Learning.
  <br><br>
  About me : Principal DevOps Cloud Engineer prepared to become a leader in the field of software architecture and development. An innovator with a talent for applying creative solutions to technical problems, and a knack for communicating complex concepts concisely. Highly expert in Kubernetes. 
  <br><br>
  Certifications : AWS Solution Architect , Certiified Kubernetes Applicatiion Developer , Certiified Kubernetes Administrator
  <br><br>
  <a href="https://www.linkedin.com/in/rahul-gupta-218b64b/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://aws.amazon.com/blogs/storage/digital-transformation-at-discover-using-aws-storage-solutions/">View My Blog on AWS</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

  <br><br>
  Contact Me: rahulgupta271@gmail.com
  <br><br>
